version: '3.8'

services:
  web:
    image: php:apache
    container_name: web-php
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "testdb"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

